/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class samjung_pimonitor_com_jniconvert */

#ifndef _Included_samjung_pimonitor_com_jniconvert
#define _Included_samjung_pimonitor_com_jniconvert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     samjung_pimonitor_com_jniconvert
 * Method:    jniConvert
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_samjung_pimonitor_com_jniconvert_jniConvert
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
